# Generated by Django 5.2.8 on 2026-02-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=20)),
                ('phone_user', models.IntegerField(unique=True)),
                ('email_user', models.CharField(max_length=20)),
                ('sub_user', models.CharField(max_length=100)),
                ('dec_user', models.TextField()),
                ('date_user', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
